### ISSUE TITLE
Training stops after 100-200 epochs

### ISSUE THREAD

**Issue by paulmis** [MCG-NJU/BasicTAD#11]
Training with

> bash tools/thumos/train_and_test_thumos_anchor_based_6fps.sh

stops after ~100-200 epochs, there is no error message. I am training on x1 A100 GPU rather than a cluster of 8, the rest is the same. Do you know why @yangmin666?

![log2](https://github.com/MCG-NJU/BasicTAD/assets/45182027/295cee68-8b47-47c4-bf86-4d2e8f5e8700)
![loss](https://github.com/MCG-NJU/BasicTAD/assets/45182027/a251aadc-7524-4b49-b403-3017865a4e73)

**Comment by yangmin666** [comment]
There is no problem with the curve in the training phase. This code uses ddp technology and has not tried to run on a single-card device. After all, not everyone has an A100 GPU.
