### ISSUE TITLE
FcosCriterion not found

### ISSUE THREAD

**Issue by SimoLoca** [MCG-NJU/BasicTAD#13]
Hi,
I was looking to try your model but I encounter an error: I was trying the model with config file **"basictad_slowonly_e700_thumos14_rgb_96win_anchor_free.py"** which in the train_engine employ the FCosCriterion.
The problem is that I cannot found that module inside the repository, can you help me please?

Thanks a lot!

**Comment by yangmin666** [comment]
Sorry for that, this problem is fixed.
