### ISSUE TITLE
lack of programs and some mistakes

### ISSUE THREAD

**Issue by hj611** [MCG-NJU/BasicTAD#2]
No module named 'vedacore.loopers.epoch_based_looper_normaltrain'
[can't open file 'tools/thumos_zhengli/test_af.py': ]  thumos_zhengli--thumos ?

**Comment by yangmin666** [comment]
Thank you for pointing these issues out!  Related issues have been fixed. We will release more elegant and complete code shortly afterwards. 

fixed issues:
1、BasicTAD/tools/thumos/ has been updated.
2、'vedacore.loopers.epoch_based_looper_normaltrain' has been deleted, which is in BasicTAD/vedacore/loopers/__init__.py

Hope this can help you.

**Comment by yangmin666** [comment]
> No module named 'vedacore.loopers.epoch_based_looper_normaltrain' [can't open file 'tools/thumos_zhengli/test_af.py': ] thumos_zhengli--thumos ?

Thank you for pointing these issues out! Related issues have been fixed. We will release more elegant and complete code shortly afterwards.

fixed issues:
1、BasicTAD/tools/thumos/ has been updated.
2、'vedacore.loopers.epoch_based_looper_normaltrain' has been deleted, which is in BasicTAD/vedacore/loopers/init.py

Hope this can help you.

**Comment by hj611** [comment]
Thanks for your response, but there are still some import mistakes in "vedacore/ops/dcn". Wish for your complete code.

**Comment by yangmin666** [comment]
> Thanks for your response, but there are still some import mistakes in "vedacore/ops/dcn". Wish for your complete code.

Maybe you missed to run "pip install -v -e .". And new code is updated now. Some issues have been eliminated. Please use the latest code.
