### ISSUE TITLE
Some quesitons: Training accuracy is too low

### ISSUE THREAD

**Issue by guaguaxyf** [MCG-NJU/BasicTAD#4]
Hi, when I train and test in AB, I found some mistakes in my result. Can you tell me the reason? 
![image](https://user-images.githubusercontent.com/90094670/200989975-c000dc06-360d-4bf1-9522-53359983d5ae.png)

**Comment by yangmin666** [comment]
I suggest you test on our public trained models of AB in 6fps to check whether there is something wrong with your data

**Comment by guaguaxyf** [comment]
Thanks for your reply! I also have some questions:
1.What is the purpose of this file and where is it?
<img width="393" alt="image" src="https://user-images.githubusercontent.com/90094670/201562199-c0182c6d-120d-4e54-a9dc-77f6b4407f0d.png">
2.Does the source code load the pretrained model, and if so, where is it? If not, what should I do?
Looking forward to your help.

**Comment by yangmin666** [comment]
> Thanks for your reply! I also have some questions: 1.What is the purpose of this file and where is it? <img alt="image" width="393" src="https://user-images.githubusercontent.com/90094670/201562199-c0182c6d-120d-4e54-a9dc-77f6b4407f0d.png"> 2.Does the source code load the pretrained model, and if so, where is it? If not, what should I do? Looking forward to your help.

1. It is only a output file in this framework which is not used, you can ignore it.    2. Of course this model load pretrained model, we use  SlowOnly  provided from facebookresearch. It seems that some users does not know how to use this pretrained model. We will supplement how to use it.

**Comment by guaguaxyf** [comment]
I have trained my data in thumos14_192_AB and thumos14_192_AF, but the value of mAP does not reach the level of paper，can you give me some suggestions? By the way, the checkpoint section in the readme gives the Baidu network disk link of the two files, what is it used for?

**Comment by yangmin666** [comment]
> I have trained my data in thumos14_192_AB and thumos14_192_AF, but the value of mAP does not reach the level of paper，can you give me some suggestions? By the way, the checkpoint section in the readme gives the Baidu network disk link of the two files, what is it used for?

1: You have not used prerained model SlowOnly 2:  Two checkpoint files are used to test THUMOS in 6 fps config.

**Comment by guaguaxyf** [comment]
I will appreciate if you supplement how to use the prerained model SlowOnly early.

**Comment by yangmin666** [comment]
> I will appreciate if you supplement how to use the pretrained model SlowOnly early.
Pretrained model SlowOnly is updated.

**Comment by guaguaxyf** [comment]
Hi，where is ～/.cache/toch/hub？

**Comment by yangmin666** [comment]
> Hi，where is ～/.cache/toch/hub？

![1](https://user-images.githubusercontent.com/33199285/201863146-743e8cc5-e283-403e-a417-2dbd11a9f7ad.jpg)

**Comment by guaguaxyf** [comment]
Do I need to add code about the pretrained model SlowOnly to configs?
<img width="471" alt="image" src="https://user-images.githubusercontent.com/90094670/203080474-de2a119d-f88f-41f5-9237-cba3d803eb03.png">

**Comment by guaguaxyf** [comment]
After I replaced the pretrained model as you suggested, the test results are still very low especially in AB 6ftps.

**Comment by guaguaxyf** [comment]
I think my configs are right, the right .pth file means?

**Comment by yangmin666** [comment]
> After I replaced the pretrained model as you suggested, the test results are still very low especially in AB 6ftps.

I suggest you check your THUMOS frames data first. For example, each frame is 320x180, and 6fps is matched.

**Comment by yangmin666** [comment]
> I think my configs are right, the right .pth file means?

epoch_300_weights.pth

**Comment by guaguaxyf** [comment]
> > I think my configs are right, the right .pth file means?
> 
> epoch_300_weights.pth

Using _**CUDA_VISIBLE_DEVICES=0 python tools/thumos/test_ab.py configs/trainval/basictad/thumos14/basictad_slowonly_e700_thumos14_rgb_192win_anchor_based.py anchor_based_6fps/ epoch_300_weights.pth**_ is fine to reference the test results of this weight file. But there is a problem with the test results of the 12 weight files produced by my training.

**Comment by yangmin666** [comment]
> 


> > > I think my configs are right, the right .pth file means?
> > 
> > 
> > epoch_300_weights.pth
> 
> Using _**CUDA_VISIBLE_DEVICES=0 python tools/thumos/test_ab.py configs/trainval/basictad/thumos14/basictad_slowonly_e700_thumos14_rgb_192win_anchor_based.py anchor_based_6fps/ epoch_300_weights.pth**_ is fine to reference the test results of this weight file. But there is a problem with the test results of the 12 weight files produced by my training.

"But there is a problem with the test results of the 12 weight files produced by my training."  You mean that 300_weight.pth provides the right answer. But you can not train your own results as well as 300_weight.pth right?

**Comment by shiyi-z** [comment]
hi! did you fix this issue? i have the same problem. the accuracy of the AF 6fps is 56.3.  i used the checkpoint provided by baidu cloud in the readme and the data is 6fps.
![anchor_free-6fps_device0123](https://user-images.githubusercontent.com/79558156/219546397-f4c4ad49-b2f8-49f3-b409-653572e9a491.jpg)

**Comment by guaguaxyf** [comment]
> 

no. My results and yours are basically the same, the accuracy under the same conditions is rounded to 56.3. only AF can run through. when testing AB, the test ends with task 53/212.
<img width="327" alt="image" src="https://user-images.githubusercontent.com/90094670/219637999-646be101-16ca-4b31-a8cb-0dc6f3dbc24f.png">

**Comment by guaguaxyf** [comment]
> hi! did you fix this issue? i have the same problem. the accuracy of the AF 6fps is 56.3. i used the checkpoint provided by baidu cloud in the readme and the data is 6fps. ![anchor_free-6fps_device0123](https://user-images.githubusercontent.com/79558156/219546397-f4c4ad49-b2f8-49f3-b409-653572e9a491.jpg)

no. My results and yours are basically the same, the accuracy under the same conditions is rounded to 56.3. only AF can run through. when testing AB, the test ends with task 53/212.
<img width="305" alt="image" src="https://user-images.githubusercontent.com/90094670/219638595-3d256e9c-a71f-42b1-99e6-be4d9815defb.png">
