### ISSUE TITLE
why _simple_infer only returns results of the FIRSAT video?

### ISSUE THREAD

**Issue by makecent** [MCG-NJU/BasicTAD#6]
https://github.com/MCG-NJU/BasicTAD/blob/bd9a1522da3d7675e079272e80e0281fa55f04be/vedatad/engines/infer_engine.py#L68-L70

As shown in above code. The `_simple_infer` function in `infer_engine.py` simply only handle the first video and ignore the rest. This would only work when the `batch_size=1`. But in the config:
https://github.com/MCG-NJU/BasicTAD/blob/bd9a1522da3d7675e079272e80e0281fa55f04be/configs/trainval/basictad/thumos14/basictad_slowonly_e700_thumos14_rgb_96win_anchor_based.py#L11-L13

The `batch_size` equals `2`

**Comment by yangmin666** [comment]
There is no relationship between the two codes. self._simple_infer is worked for ActivityNet which has not been published. New code will be released soon, with more powerful performance.

**Comment by makecent** [comment]
Thanks for the explanation.
